### ISSUE TITLE
Feature Request: Add Lists with ABP Syntax

### ISSUE THREAD

**Issue by plainasday** [elliotwutingfeng/Inversion-DNSBL-Blocklists#1]
Thank you so much for this project. It is a fantastic idea and executed very well. 

I would like to request that two additional lists be made of the Inversion Google Hosts and Inversion Google Hosts Lite lists that adhere to [AdBlock Plus Syntax](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters). This would allow the lists to be used to their fullest potential while using AdGuard products. 

As the hosts lists currently stand, they are usable on AdGuard products but are limited. For example, the entry “google[.]com” would not block “sub.google[.]com” due to the current syntax. If the lists were also available in AdBlock Plus syntax, the entry could block subdomains as well. This would be particularly helpful on mobile but also helpful on AdGuard Home. 

AdGuard has made a couple tools that may be helpful:
1. [Hostlist compiler](https://github.com/AdguardTeam/HostlistCompiler) 
2. [Filters compiler](https://github.com/AdguardTeam/FiltersCompiler) 

Thank you for your consideration.

**Comment by elliotwutingfeng** [comment]
Hi, thanks for the suggestion. I've added the ABP syntax variants. Do let me know if the syntax is correct.

**Comment by plainasday** [comment]
Thank you very much for responding and for responding so quickly.  As far as I know, the new filters look perfect.
